country_city_mapping = {
    'United Arab Emirates': ['Abu Dhabi', 'Dubai'],
    'Sri Lanka': ['Colombo', 'Kandy', 'Dambulla', 'Galle', 'Hambantota', 'Kathmandu'],
    'Papua New Guinea': ['Port Moresby'],
    'South Africa': ['Cape Town', 'Potchefstroom', 'St Kitts', 'Hamilton', 'Benoni', 'Johannesburg', 'Paarl' , 'Durban', 'Bloemfontein', 'Port Elizabeth', 'Centurion', 'Gqeberha',],
    'Kenya': ['Nairobi'],
    'England': ['Ayr', 'Nottingham', 'Cardiff', 'Leeds', 'Birmingham', 'Southampton', 'London', 'Chester-le-Street', 'Manchester', 'Belfast', 'Taunton', 'Bristol', 'Leeds', 'Chelmsford', 'Edinburgh'],
    'Oman': ['Al Amarat'],
    'Zimbabwe': ['Harare', 'Bulawayo'],
    'Afghanistan': [],
    'United States of America': ['Providence', 'Toronto', 'Lauderhill'],
    'West Indies': ['Dominica', 'Trinidad', 'Gros Islet', 'King City', 'Tarouba', "St George's", 'St Lucia', 'Chester-le-Street', 'Jamaica', 'Antigua', 'Kingston', 'North Sound', 'Bridgetown', 'Grenada'],
    'Hong Kong': ['Hong Kong'],
    'Jersey': [],
    'New Zealand': ['Nelson', 'Queenstown', 'Whangarei', 'Dunedin', 'Mount Maunganui', 'Lincoln'],
    'Bangladesh': ['Chittagong', 'Mirpur', 'Sylhet', 'Bogra', 'Dhaka', 'Chattogram', 'Fatullah', 'Khulna'],
    'Netherlands': ['Rotterdam', 'Utrecht', 'Deventer', 'Amstelveen'],
    'Scotland': ['Glasgow', 'Aberdeen', 'Edinburgh'],
    'Bermuda': [],
    'Ireland': ['Dublin'],
    'India': ['Vadodara', 'Faridabad', 'Ahmedabad', 'Kolkata', 'Rajkot', 'Dharamsala', 'Kochi', 'Ranchi', 'Guwahati', 'Chandigarh', 'Lucknow', 'Indore', 'Delhi', 'Thiruvananthapuram', 'Jamshedpur', 'Visakhapatnam', 'Greater Noida', 'Cuttack', 'Mumbai', 'Pune', 'Guwahati', 'Jaipur', 'Kolkata'],
    'Australia': ['Perth', 'Adelaide', 'Brisbane', 'Sydney', 'Melbourne', 'Canberra', 'Hobart', 'Townsville', 'Cairns'],
    'Nepal': ['Kirtipur', 'Kathmandu'],
    'Namibia': ['Windhoek'],
    'Canada': ['King City', 'Toronto'],
    'Pakistan': ['Peshawar', 'Faisalabad', 'Lahore', 'Karachi', 'Multan'],
}